spring:
  application:
    name: tour
  datasource:
    url: jdbc:mysql://localhost:3306/microService
    username: root
    password: root123456
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: ${PORT:8081}
